version: "2.1"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    command: "npm run start"
    volumes:
      - ./server:/var/www/server
    ports:
        - 8443:8443

  nginx:
    depends_on:
        - client
        - server
    build: ./etc/nginx
    volumes:
      - ./client:/var/www/client
    ports:
        - 8082:80
        - 8083:443

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - ./client:/var/www/client
    depends_on:
      - server